
[package]
name = "payment-splitter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "payment_splitter"

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []
